
#TODO - Add functionality for supporting iface_ and settings
specific_types = [
    ("CompositorNodeMixRGB", {"label":'iface_("Mix Color")'}),
    ("CompositorNodeSwitchView", {"label":'iface_("Switch Stereo View")'})
]

items = [
    "CompositorNodeBokehImage",
    "CompositorNodeImage",
    "CompositorNodeMask",
    "CompositorNodeMovieClip",
    "CompositorNodeTexture",
    "CompositorNodeRGB",
    "CompositorNodeValue",
    "CompositorNodeRLayers",
    "CompositorNodeSceneTime",
    "CompositorNodeTime",
    "CompositorNodeComposite",
    "CompositorNodeSplitViewer",
    "CompositorNodeViewer",
    "CompositorNodeOutputFile",
    "CompositorNodePremulKey",
    "CompositorNodeValToRGB",
    "CompositorNodeConvertColorSpace",
    "CompositorNodeSetAlpha",
    "CompositorNodeInvert",
    "CompositorNodeRGBToBW",
    "CompositorNodeBrightContrast",
    "CompositorNodeColorBalance",
    "CompositorNodeColorCorrection",
    "CompositorNodeExposure",
    "CompositorNodeGamma",
    "CompositorNodeHueCorrect",
    "CompositorNodeHueSat",
    "CompositorNodeCurveRGB",
    "CompositorNodeTonemap",
    "CompositorNodeAlphaOver",
    "CompositorNodeCombineColor",
    "CompositorNodeSeparateColor",
    "CompositorNodeZcombine",
    "CompositorNodeAntiAliasing",
    "CompositorNodeDenoise",
    "CompositorNodeDespeckle",
    "CompositorNodeDilateErode",
    "CompositorNodeInpaint",
    "CompositorNodeFilter",
    "CompositorNodeGlare",
    "CompositorNodeKuwahara",
    "CompositorNodePixelate",
    "CompositorNodePosterize",
    "CompositorNodeSunBeams",
    "CompositorNodeBilateralblur",
    "CompositorNodeBlur",
    "CompositorNodeBokehBlur",
    "CompositorNodeDefocus",
    "CompositorNodeDBlur",
    "CompositorNodeVecBlur",
    "CompositorNodeChannelMatte",
    "CompositorNodeChromaMatte",
    "CompositorNodeColorMatte",
    "CompositorNodeColorSpill",
    "CompositorNodeDiffMatte",
    "CompositorNodeDistanceMatte",
    "CompositorNodeKeying",
    "CompositorNodeKeyingScreen",
    "CompositorNodeLumaMatte",
    "CompositorNodeCryptomatteV2",
    "CompositorNodeCryptomatte",
    "CompositorNodeBoxMask",
    "CompositorNodeEllipseMask",
    "CompositorNodeDoubleEdgeMask",
    "CompositorNodeIDMask",
    "CompositorNodePlaneTrackDeform",
    "CompositorNodeStabilize",
    "CompositorNodeTrackPos",
    "CompositorNodeRotate",
    "CompositorNodeScale",
    "CompositorNodeTransform",
    "CompositorNodeTranslate",
    "CompositorNodeCornerPin",
    "CompositorNodeCrop",
    "CompositorNodeDisplace",
    "CompositorNodeFlip",
    "CompositorNodeMapUV",
    "CompositorNodeLensdist",
    "CompositorNodeMovieDistortion",
    "CompositorNodeMapRange",
    "CompositorNodeMapValue",
    "CompositorNodeMath",
    "CompositorNodeLevels",
    "CompositorNodeNormalize",
    "CompositorNodeSwitch",
    "CompositorNodeCombineXYZ",
    "CompositorNodeSeparateXYZ",
    "CompositorNodeNormal",
    "CompositorNodeCurveVec",
]

all_items = [
    (items, None, None)
]