from ..utils import in_nodegroup

group_nodes = [
    "NodeGroupInput",
    "NodeGroupOutput",
]

#Note - Structure -> (idname, {properties})
specific_types = [
    ("CompositorNodeMixRGB", {"label": "Mix Color", "subtypes":("blend_type",)}),
    ("CompositorNodeSwitchView", {"label": "Switch Stereo View"})
]

basic_subtypes = [
    ("CompositorNodePremulKey", {"subtypes":("mapping",)}),
    ("CompositorNodeSetAlpha", {"subtypes":("mode",)}),
    ("CompositorNodeDefocus", {"subtypes":("bokeh",)}),
    ("CompositorNodeDenoise", {"subtypes":("prefilter",)}),
    ("CompositorNodeDilateErode", {"subtypes":("mode",)}),
    ("CompositorNodeGlare", {"subtypes":("glare_type",)}),
    ("CompositorNodeRotate", {"subtypes":("filter_type",)}),
    ("CompositorNodeScale", {"subtypes":("space",)}),
    ("CompositorNodeTransform", {"subtypes":("filter_type",)}),
    ("CompositorNodeTranslate", {"subtypes":("wrap_axis",)}),
    ("CompositorNodeFlip", {"subtypes":("axis",)}),
    ("CompositorNodeBlur", {"subtypes":("filter_type",)}),
    ("CompositorNodeKuwahara", {"subtypes":("variation",)}),
    ("CompositorNodeLevels", {"subtypes":("channel",)}),
    ("CompositorNodeMath", {"subtypes":("operation",)}),
    ("CompositorNodeCombineColor", {"subtypes":("mode",)}),
    ("CompositorNodeSeparateColor", {"subtypes":("mode",)}),
    ("CompositorNodeFilter", {"subtypes":("filter_type",)}),
]

items = [
    "CompositorNodeBokehImage",
    "CompositorNodeImage",
    "CompositorNodeMask",
    "CompositorNodeMovieClip",
    "CompositorNodeTexture",
    "CompositorNodeRGB",
    "CompositorNodeValue",
    "CompositorNodeRLayers",
    "CompositorNodeSceneTime",
    "CompositorNodeTime",
    "CompositorNodeComposite",
    "CompositorNodeSplitViewer",
    "CompositorNodeViewer",
    "CompositorNodeOutputFile",
    "CompositorNodeValToRGB",
    "CompositorNodeConvertColorSpace",
    "CompositorNodeInvert",
    "CompositorNodeRGBToBW",
    "CompositorNodeBrightContrast",
    "CompositorNodeColorBalance",
    "CompositorNodeColorCorrection",
    "CompositorNodeExposure",
    "CompositorNodeGamma",
    "CompositorNodeHueCorrect",
    "CompositorNodeHueSat",
    "CompositorNodeCurveRGB",
    "CompositorNodeTonemap",
    "CompositorNodeAlphaOver",
    "CompositorNodeZcombine",
    "CompositorNodeAntiAliasing",
    "CompositorNodeDespeckle",
    "CompositorNodeInpaint",
    "CompositorNodePixelate",
    "CompositorNodePosterize",
    "CompositorNodeSunBeams",
    "CompositorNodeBilateralblur",
    "CompositorNodeBokehBlur",
    "CompositorNodeDBlur",
    "CompositorNodeVecBlur",
    "CompositorNodeChannelMatte",
    "CompositorNodeChromaMatte",
    "CompositorNodeColorMatte",
    "CompositorNodeColorSpill",
    "CompositorNodeDiffMatte",
    "CompositorNodeDistanceMatte",
    "CompositorNodeKeying",
    "CompositorNodeKeyingScreen",
    "CompositorNodeLumaMatte",
    "CompositorNodeCryptomatteV2",
    "CompositorNodeCryptomatte",
    "CompositorNodeBoxMask",
    "CompositorNodeEllipseMask",
    "CompositorNodeDoubleEdgeMask",
    "CompositorNodeIDMask",
    "CompositorNodePlaneTrackDeform",
    "CompositorNodeStabilize",
    "CompositorNodeTrackPos",
    "CompositorNodeCornerPin",
    "CompositorNodeCrop",
    "CompositorNodeDisplace",
    "CompositorNodeMapUV",
    "CompositorNodeLensdist",
    "CompositorNodeMovieDistortion",
    "CompositorNodeMapRange",
    "CompositorNodeMapValue",
    "CompositorNodeNormalize",
    "CompositorNodeSwitch",
    "CompositorNodeCombineXYZ",
    "CompositorNodeSeparateXYZ",
    "CompositorNodeNormal",
    "CompositorNodeCurveVec",
]

all_items = [
    (items, None, None),
    (specific_types, None, None),
    (basic_subtypes, None, None),
    (group_nodes, in_nodegroup, None),
]