
zones = [
    ("Simulation Zone", {"label": "Simulation Zone", "function":"create_zone", "settings":{"input_type": "GeometryNodeSimulationInput", "output_type": "GeometryNodeSimulationOutput"}}),
    ("Repeat Zone", {"label": "Repeat Zone", "function":"create_zone", "settings":{"input_type": "GeometryNodeRepeatInput", "output_type": "GeometryNodeRepeatOutput"}})
]

#Note - Structure -> (idname, {properties})
specific_types = [
    "ShaderNodeMix", #Note - Include as default entry
    ("ShaderNodeMix", {"label": "Mix Vector", "settings":{"data_type": "VECTOR"}, "subtypes":("factor_mode",) }),
    ("ShaderNodeMix", {"label": "Mix Color", "settings":{"data_type": "RGBA"}, "subtypes":("blend_type",)}),
    ("ShaderNodeMix", {"label": "Mix Rotation", "settings":{"data_type": "ROTATION"}}),

    "GeometryNodeRaycast", #Note - Include as default entry
    ("GeometryNodeRaycast", {"label": "Raycast Nearest", "settings":{"mapping": "NEAREST"}, "subtypes":("data_type",)}),
    ("GeometryNodeRaycast", {"label": "Raycast Interpolated", "settings":{"mapping": "INTERPOLATED"}, "subtypes":("data_type",)}),

    ("ShaderNodeMapRange", {"label": "Map Range - Float", "settings":{"data_type": "FLOAT"}, "subtypes":("interpolation_type",)}),
    ("ShaderNodeMapRange", {"label": "Map Range - Vector", "settings":{"data_type": "FLOAT_VECTOR"}, "subtypes":("interpolation_type",)}),
 
    #TODO - Add function node subtypes
    "FunctionNodeCompare", #Note - Include as default entry
]

def is_tool(context):
    return context.space_data.geometry_nodes_type == 'TOOL'

def use_experimental_volume_nodes(context):
    return context.preferences.experimental.use_new_volume_nodes

items = [
    "GeometryNodeRemoveAttribute",
    "ShaderNodeValToRGB",
    "ShaderNodeRGBCurve",
    "GeometryNodeInputCurveHandlePositions",
    "GeometryNodeCurveLength",
    "GeometryNodeInputTangent",
    "GeometryNodeInputCurveTilt",
    "GeometryNodeCurveEndpointSelection",
    "GeometryNodeSplineLength",
    "GeometryNodeSplineParameter",
    "GeometryNodeInputSplineResolution",
    "GeometryNodeSampleCurve",
    "GeometryNodeSetCurveNormal",
    "GeometryNodeSetCurveRadius",
    "GeometryNodeSetCurveTilt",
    "GeometryNodeSetCurveHandlePositions",
    "GeometryNodeSetSplineResolution",
    "GeometryNodeCurveToMesh",
    "GeometryNodeCurveToPoints",        
    "GeometryNodeDeformCurvesOnSurface",
    "GeometryNodeFillCurve",
    "GeometryNodeInterpolateCurves",
    "GeometryNodeResampleCurve",
    "GeometryNodeReverseCurve",
    "GeometryNodeSubdivideCurve",
    "GeometryNodeTrimCurve",
    "GeometryNodeCurveArc",
    "GeometryNodeCurvePrimitiveBezierSegment",
    "GeometryNodeCurvePrimitiveLine",
    "GeometryNodeCurveSpiral",
    "GeometryNodeCurveQuadraticBezier",
    "GeometryNodeCurvePrimitiveQuadrilateral",
    "GeometryNodeCurveStar",
    "GeometryNodeCurveOfPoint",
    "GeometryNodeOffsetPointInCurve",
    "GeometryNodePointsOfCurve",
    "GeometryNodeGeometryToInstance",
    "GeometryNodeJoinGeometry",
    "GeometryNodeInputID",
    "GeometryNodeInputIndex",
    "GeometryNodeInputNormal",
    "GeometryNodeInputPosition",
    "GeometryNodeInputRadius",
    "GeometryNodeSetID",
    "GeometryNodeSetPosition",
    "GeometryNodeBoundBox",
    "GeometryNodeConvexHull",
    "GeometryNodeDeleteGeometry",
    "GeometryNodeTransform",
    "GeometryNodeSeparateComponents",
    "GeometryNodeIndexOfNearest",
    "FunctionNodeInputBool",
    "FunctionNodeInputColor",
    "GeometryNodeInputImage",
    "FunctionNodeInputInt",
    "GeometryNodeInputMaterial",
    "FunctionNodeInputString",
    "ShaderNodeValue",
    "FunctionNodeInputVector",
    "NodeGroupInput",
    "GeometryNodeCollectionInfo",
    "GeometryNodeImageInfo",
    "GeometryNodeIsViewport",
    "GeometryNodeObjectInfo",
    "GeometryNodeInputSceneTime",
    "GeometryNodeSelfObject",
    "GeometryNodeInstanceOnPoints",
    "GeometryNodeInstancesToPoints",
    "GeometryNodeRealizeInstances",
    "GeometryNodeRotateInstances",
    "GeometryNodeScaleInstances",
    "GeometryNodeTranslateInstances",
    "GeometryNodeInputInstanceRotation",
    "GeometryNodeInputInstanceScale",
    "GeometryNodeReplaceMaterial",
    "GeometryNodeInputMaterialIndex",
    "GeometryNodeMaterialSelection",
    "GeometryNodeSetMaterial",
    "GeometryNodeSetMaterialIndex",
    "GeometryNodeInputMeshEdgeAngle",
    "GeometryNodeInputMeshEdgeNeighbors",
    "GeometryNodeInputMeshEdgeVertices",
    "GeometryNodeEdgesToFaceGroups",
    "GeometryNodeInputMeshFaceArea",
    "GeometryNodeMeshFaceSetBoundaries",
    "GeometryNodeInputMeshFaceNeighbors",
    "GeometryNodeInputMeshFaceIsPlanar",
    "GeometryNodeInputShadeSmooth",
    "GeometryNodeInputEdgeSmooth",
    "GeometryNodeInputMeshIsland",
    "GeometryNodeInputShortestEdgePaths",
    "GeometryNodeInputMeshVertexNeighbors",
    "GeometryNodeSetShadeSmooth",
    "GeometryNodeDualMesh",
    "GeometryNodeEdgePathsToCurves",
    "GeometryNodeEdgePathsToSelection",
    "GeometryNodeExtrudeMesh",
    "GeometryNodeMeshToCurve",
    "GeometryNodeMeshToPoints",
    "GeometryNodeMeshToVolume",
    "GeometryNodeSplitEdges",
    "GeometryNodeSubdivideMesh",
    "GeometryNodeSubdivisionSurface",
    "GeometryNodeTriangulate",
    "GeometryNodeMeshCone",
    "GeometryNodeMeshCube",
    "GeometryNodeMeshCylinder",
    "GeometryNodeMeshGrid",
    "GeometryNodeMeshIcoSphere",
    "GeometryNodeMeshLine",
    "GeometryNodeMeshUVSphere",
    "GeometryNodeCornersOfEdge",
    "GeometryNodeCornersOfFace",
    "GeometryNodeCornersOfVertex",
    "GeometryNodeEdgesOfCorner",
    "GeometryNodeEdgesOfVertex",
    "GeometryNodeOffsetCornerInFace",
    "GeometryNodeVertexOfCorner",
    "NodeGroupOutput",
    "GeometryNodeViewer",
    "GeometryNodeDistributePointsInVolume",
    "GeometryNodeDistributePointsOnFaces",
    "GeometryNodePoints",
    "GeometryNodePointsToCurves",
    "GeometryNodePointsToVertices",
    "GeometryNodePointsToVolume",
    "GeometryNodeSetPointRadius",
    "GeometryNodeStringJoin",
    "FunctionNodeReplaceString",
    "FunctionNodeSliceString",
    "FunctionNodeStringLength",
    "GeometryNodeStringToCurves",
    "FunctionNodeValueToString",
    "FunctionNodeInputSpecialCharacters",
    "ShaderNodeTexBrick",
    "ShaderNodeTexChecker",
    "ShaderNodeTexGradient",
    "GeometryNodeImageTexture",
    "ShaderNodeTexMagic",
    "ShaderNodeTexMusgrave",
    "ShaderNodeTexNoise",
    "ShaderNodeTexVoronoi",
    "ShaderNodeTexWave",
    "ShaderNodeTexWhiteNoise",
    "FunctionNodeAlignEulerToVector",
    "FunctionNodeAxisAngleToRotation",
    "FunctionNodeEulerToRotation",
    "FunctionNodeInvertRotation",
    "FunctionNodeRotateEuler",
    "FunctionNodeRotateVector",
    "FunctionNodeRotationToAxisAngle",
    "FunctionNodeRotationToEuler",
    "FunctionNodeRotationToQuaternion",
    "FunctionNodeQuaternionToRotation",
    "ShaderNodeFloatCurve",
    "GeometryNodeUVPackIslands",
    "ShaderNodeVectorCurve",
    "ShaderNodeCombineXYZ",
    "ShaderNodeSeparateXYZ",
    "GeometryNodeVolumeCube",
    "GeometryNodeVolumeToMesh",
]

has_subtypes = [
    ("ShaderNodeClamp", {"subtypes":("clamp_type",)}),
    ("GeometryNodeSwitch", {"subtypes":("input_type",)}),
    ("GeometryNodeFilletCurve", {"subtypes":("mode",)}),
    ("GeometryNodeUVUnwrap", {"subtypes":("method",)}),
    ("ShaderNodeMath", {"subtypes":("operation",)}),
    ("ShaderNodeVectorMath", {"subtypes":("operation",)}),
    ("FunctionNodeBooleanMath", {"subtypes":("operation",)}),
    ("GeometryNodeAttributeDomainSize", {"subtypes":("component",)}),
    ("GeometryNodeProximity", {"subtypes":("target_element",)}),
    ("GeometryNodeSampleNearest", {"subtypes":("domain",)}),
    ("GeometryNodeCurveSplineType", {"subtypes":("spline_type",)}),
    ("GeometryNodeCurveSetHandles", {"subtypes":("handle_type",)}),
    ("GeometryNodeCurveHandleTypeSelection", {"subtypes":("handle_type",)}),
    ("GeometryNodeMeshBoolean", {"subtypes":("operation",)}),
    ("FunctionNodeCombineColor", {"subtypes":("mode",)}),
    ("FunctionNodeSeparateColor", {"subtypes":("mode",)}),
    ("GeometryNodeMergeByDistance", {"subtypes":("mode",)}),
    ("GeometryNodeSeparateGeometry", {"subtypes":("domain",)}),
    ("GeometryNodeDuplicateElements", {"subtypes":("domain",)}),
    ("FunctionNodeFloatToInt", {"subtypes":("rounding_mode",)}),
    ("ShaderNodeVectorRotate", {"subtypes":("rotation_type",)}),
    ("GeometryNodeScaleElements", {"subtypes":("domain",)}), #TODO - Add scale_mode subtype as well

    #TODO - Add filtering for excluding subtypes as these nodes seem to have a filter that's inaccessible to the API
    ("FunctionNodeRandomValue", {"subtypes":("data_type",)}),
    ("GeometryNodeSampleNearestSurface", {"subtypes":("data_type",)}),
    ("GeometryNodeSampleUVSurface", {"subtypes":("data_type",)}),
    ("GeometryNodeBlurAttribute", {"subtypes":("data_type",)}),
    ("GeometryNodeInputNamedAttribute", {"subtypes":("data_type",)}),
    ("GeometryNodeAttributeStatistic", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeStoreNamedAttribute", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeCaptureAttribute", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeFieldOnDomain", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeSampleIndex", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeFieldAtIndex", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
    ("GeometryNodeAccumulateField", {"subtypes":("data_type",)}),    #TODO - Add domain subtype as well
]

#Note - Included when context.preferences.experimental.use_new_volume_nodes is True:
experimental_volumes = [
    "GeometryNodeMeanFilterSDFVolume",
    "GeometryNodeOffsetSDFVolume",
    "GeometryNodeSampleVolume",
    "GeometryNodeSDFVolumeSphere",
    "GeometryNodeInputSignedDistance",
    "GeometryNodePointsToSDFVolume",
    "GeometryNodeMeshToSDFVolume",
]

#Note - Included when context.space_data.geometry_nodes_type == 'TOOL':
tool_nodes = [
    "GeometryNodeToolFaceSet",
    "GeometryNodeToolSetFaceSet",
    "GeometryNodeTool3DCursor",
    "GeometryNodeToolSetSelection",
    "GeometryNodeToolSelection",
]


all_items = [
    (items, None, None),
    (zones, None, None),
    (has_subtypes, None, None),
    (specific_types, None, None),
    (tool_nodes, is_tool, None),
    (experimental_volumes, use_experimental_volume_nodes, None),
]